// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnalysisJob = `-- name: CreateAnalysisJob :exec
INSERT INTO analysis_jobs (
    id,
    analysis_id,
    status,
    request,
    error_message,
    attempt,
    phase,
    progress_percent,
    phase_started_at,
    created_at,
    started_at,
    finished_at
) VALUES (
    $1,
    $2,
    $3,
    $4::jsonb,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
`

type CreateAnalysisJobParams struct {
	ID              string             `json:"id"`
	AnalysisID      pgtype.Text        `json:"analysis_id"`
	Status          string             `json:"status"`
	Request         []byte             `json:"request"`
	ErrorMessage    string             `json:"error_message"`
	Attempt         int32              `json:"attempt"`
	Phase           string             `json:"phase"`
	ProgressPercent int32              `json:"progress_percent"`
	PhaseStartedAt  pgtype.Timestamptz `json:"phase_started_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) CreateAnalysisJob(ctx context.Context, arg CreateAnalysisJobParams) error {
	_, err := q.db.Exec(ctx, createAnalysisJob,
		arg.ID,
		arg.AnalysisID,
		arg.Status,
		arg.Request,
		arg.ErrorMessage,
		arg.Attempt,
		arg.Phase,
		arg.ProgressPercent,
		arg.PhaseStartedAt,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const findAnalysisJob = `-- name: FindAnalysisJob :one
SELECT
    id,
    analysis_id,
    status,
    request,
    error_message,
    attempt,
    phase,
    progress_percent,
    phase_started_at,
    created_at,
    started_at,
    finished_at
FROM analysis_jobs
WHERE id = $1
`

type FindAnalysisJobRow struct {
	ID              string             `json:"id"`
	AnalysisID      pgtype.Text        `json:"analysis_id"`
	Status          string             `json:"status"`
	Request         []byte             `json:"request"`
	ErrorMessage    string             `json:"error_message"`
	Attempt         int32              `json:"attempt"`
	Phase           string             `json:"phase"`
	ProgressPercent int32              `json:"progress_percent"`
	PhaseStartedAt  pgtype.Timestamptz `json:"phase_started_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) FindAnalysisJob(ctx context.Context, id string) (FindAnalysisJobRow, error) {
	row := q.db.QueryRow(ctx, findAnalysisJob, id)
	var i FindAnalysisJobRow
	err := row.Scan(
		&i.ID,
		&i.AnalysisID,
		&i.Status,
		&i.Request,
		&i.ErrorMessage,
		&i.Attempt,
		&i.Phase,
		&i.ProgressPercent,
		&i.PhaseStartedAt,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const markAnalysisJobCanceled = `-- name: MarkAnalysisJobCanceled :exec
UPDATE analysis_jobs
SET
    status = 'canceled',
    finished_at = $1
WHERE id = $2
`

type MarkAnalysisJobCanceledParams struct {
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	ID         string             `json:"id"`
}

func (q *Queries) MarkAnalysisJobCanceled(ctx context.Context, arg MarkAnalysisJobCanceledParams) error {
	_, err := q.db.Exec(ctx, markAnalysisJobCanceled, arg.FinishedAt, arg.ID)
	return err
}

const markAnalysisJobCompleted = `-- name: MarkAnalysisJobCompleted :exec
UPDATE analysis_jobs
SET
    status = 'completed',
    analysis_id = $1,
    finished_at = $2,
    phase = 'done',
    progress_percent = 100
WHERE id = $3
`

type MarkAnalysisJobCompletedParams struct {
	AnalysisID pgtype.Text        `json:"analysis_id"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	ID         string             `json:"id"`
}

func (q *Queries) MarkAnalysisJobCompleted(ctx context.Context, arg MarkAnalysisJobCompletedParams) error {
	_, err := q.db.Exec(ctx, markAnalysisJobCompleted, arg.AnalysisID, arg.FinishedAt, arg.ID)
	return err
}

const markAnalysisJobFailed = `-- name: MarkAnalysisJobFailed :exec
UPDATE analysis_jobs
SET
    status = 'failed',
    error_message = $1,
    finished_at = $2
WHERE id = $3
`

type MarkAnalysisJobFailedParams struct {
	ErrorMessage string             `json:"error_message"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ID           string             `json:"id"`
}

func (q *Queries) MarkAnalysisJobFailed(ctx context.Context, arg MarkAnalysisJobFailedParams) error {
	_, err := q.db.Exec(ctx, markAnalysisJobFailed, arg.ErrorMessage, arg.FinishedAt, arg.ID)
	return err
}

const markAnalysisJobPhase = `-- name: MarkAnalysisJobPhase :exec
UPDATE analysis_jobs
SET
    phase = $1,
    progress_percent = $2,
    phase_started_at = $3
WHERE id = $4
`

type MarkAnalysisJobPhaseParams struct {
	Phase           string             `json:"phase"`
	ProgressPercent int32              `json:"progress_percent"`
	PhaseStartedAt  pgtype.Timestamptz `json:"phase_started_at"`
	ID              string             `json:"id"`
}

func (q *Queries) MarkAnalysisJobPhase(ctx context.Context, arg MarkAnalysisJobPhaseParams) error {
	_, err := q.db.Exec(ctx, markAnalysisJobPhase,
		arg.Phase,
		arg.ProgressPercent,
		arg.PhaseStartedAt,
		arg.ID,
	)
	return err
}

const markAnalysisJobRunning = `-- name: MarkAnalysisJobRunning :exec
UPDATE analysis_jobs
SET
    status = 'running',
    attempt = attempt + 1,
    started_at = $1,
    phase = 'collecting_signals',
    progress_percent = 0,
    phase_started_at = $1
WHERE id = $2
`

type MarkAnalysisJobRunningParams struct {
	StartedAt pgtype.Timestamptz `json:"started_at"`
	ID        string             `json:"id"`
}

func (q *Queries) MarkAnalysisJobRunning(ctx context.Context, arg MarkAnalysisJobRunningParams) error {
	_, err := q.db.Exec(ctx, markAnalysisJobRunning, arg.StartedAt, arg.ID)
	return err
}
