// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis_delete.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAnalysesKeepingNewest = `-- name: DeleteAnalysesKeepingNewest :execrows
DELETE FROM analyses
WHERE id IN (
    SELECT id FROM analyses
    ORDER BY created_at DESC
    OFFSET $1
)
`

func (q *Queries) DeleteAnalysesKeepingNewest(ctx context.Context, keepCount int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnalysesKeepingNewest, keepCount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAnalysesOlderThan = `-- name: DeleteAnalysesOlderThan :execrows
DELETE FROM analyses WHERE created_at < $1
`

func (q *Queries) DeleteAnalysesOlderThan(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnalysesOlderThan, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAnalysisByID = `-- name: DeleteAnalysisByID :execrows
DELETE FROM analyses WHERE id = $1
`

func (q *Queries) DeleteAnalysisByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnalysisByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
