// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id, name, key_hash, scope, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAPIKeyParams struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	KeyHash   string             `json:"key_hash"`
	Scope     string             `json:"scope"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.ID,
		arg.Name,
		arg.KeyHash,
		arg.Scope,
		arg.CreatedAt,
	)
	return err
}

const findAPIKeyByHash = `-- name: FindAPIKeyByHash :one
SELECT id, name, key_hash, scope, created_at, last_used_at, revoked_at
FROM api_keys
WHERE key_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) FindAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, findAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyHash,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_hash, scope, created_at, last_used_at, revoked_at
FROM api_keys
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListAPIKeysParams struct {
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyHash,
			&i.Scope,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys
SET revoked_at = $1
WHERE id = $2 AND revoked_at IS NULL
`

type RevokeAPIKeyParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	ID        string             `json:"id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.RevokedAt, arg.ID)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = $1
WHERE id = $2
`

type TouchAPIKeyLastUsedParams struct {
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ID         string             `json:"id"`
}

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, arg TouchAPIKeyLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
