// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAuditEntry = `-- name: AppendAuditEntry :exec
INSERT INTO audit_log (
    request_id,
    api_key_id,
    actor,
    method,
    path,
    status,
    duration_ms,
    remote,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type AppendAuditEntryParams struct {
	RequestID  string             `json:"request_id"`
	ApiKeyID   string             `json:"api_key_id"`
	Actor      string             `json:"actor"`
	Method     string             `json:"method"`
	Path       string             `json:"path"`
	Status     int32              `json:"status"`
	DurationMs int64              `json:"duration_ms"`
	Remote     string             `json:"remote"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AppendAuditEntry(ctx context.Context, arg AppendAuditEntryParams) error {
	_, err := q.db.Exec(ctx, appendAuditEntry,
		arg.RequestID,
		arg.ApiKeyID,
		arg.Actor,
		arg.Method,
		arg.Path,
		arg.Status,
		arg.DurationMs,
		arg.Remote,
		arg.CreatedAt,
	)
	return err
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT id, request_id, api_key_id, actor, method, path, status, duration_ms, remote, created_at
FROM audit_log
WHERE ($1::text IS NULL OR api_key_id = $1::text)
  AND ($2::timestamptz IS NULL OR created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR created_at <= $3::timestamptz)
ORDER BY created_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListAuditEntriesParams struct {
	ApiKeyID     pgtype.Text        `json:"api_key_id"`
	FromAt       pgtype.Timestamptz `json:"from_at"`
	ToAt         pgtype.Timestamptz `json:"to_at"`
	ResultOffset int32              `json:"result_offset"`
	ResultLimit  int32              `json:"result_limit"`
}

func (q *Queries) ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEntries,
		arg.ApiKeyID,
		arg.FromAt,
		arg.ToAt,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ApiKeyID,
			&i.Actor,
			&i.Method,
			&i.Path,
			&i.Status,
			&i.DurationMs,
			&i.Remote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
