// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO analysis_chat_messages (
    analysis_id,
    role,
    content,
    evidence,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4::jsonb,
    now()
)
RETURNING id, analysis_id, role, content, evidence, created_at
`

type CreateChatMessageParams struct {
	AnalysisID string `json:"analysis_id"`
	Role       string `json:"role"`
	Content    string `json:"content"`
	Evidence   []byte `json:"evidence"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (AnalysisChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.AnalysisID,
		arg.Role,
		arg.Content,
		arg.Evidence,
	)
	var i AnalysisChatMessage
	err := row.Scan(
		&i.ID,
		&i.AnalysisID,
		&i.Role,
		&i.Content,
		&i.Evidence,
		&i.CreatedAt,
	)
	return i, err
}

const listChatMessagesByAnalysis = `-- name: ListChatMessagesByAnalysis :many
SELECT
    id,
    analysis_id,
    role,
    content,
    evidence,
    created_at
FROM (
    SELECT
        id,
        analysis_id,
        role,
        content,
        evidence,
        created_at
    FROM analysis_chat_messages
    WHERE analysis_id = $1
      AND ($2::timestamptz IS NULL OR created_at < $2::timestamptz)
    ORDER BY created_at DESC, id DESC
    LIMIT $3
) AS page
ORDER BY created_at ASC, id ASC
`

type ListChatMessagesByAnalysisParams struct {
	AnalysisID  string             `json:"analysis_id"`
	Before      pgtype.Timestamptz `json:"before"`
	ResultLimit int32              `json:"result_limit"`
}

func (q *Queries) ListChatMessagesByAnalysis(ctx context.Context, arg ListChatMessagesByAnalysisParams) ([]AnalysisChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessagesByAnalysis, arg.AnalysisID, arg.Before, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalysisChatMessage{}
	for rows.Next() {
		var i AnalysisChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.AnalysisID,
			&i.Role,
			&i.Content,
			&i.Evidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
