// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_feedback.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertChatFeedback = `-- name: UpsertChatFeedback :exec
INSERT INTO analysis_chat_feedback (
    analysis_id,
    message_id,
    useful,
    reason,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $5
)
ON CONFLICT (analysis_id, message_id) DO UPDATE
SET
    useful = EXCLUDED.useful,
    reason = EXCLUDED.reason,
    updated_at = EXCLUDED.updated_at
`

type UpsertChatFeedbackParams struct {
	AnalysisID string             `json:"analysis_id"`
	MessageID  int64              `json:"message_id"`
	Useful     bool               `json:"useful"`
	Reason     string             `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertChatFeedback(ctx context.Context, arg UpsertChatFeedbackParams) error {
	_, err := q.db.Exec(ctx, upsertChatFeedback,
		arg.AnalysisID,
		arg.MessageID,
		arg.Useful,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}
