// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_configurations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateLLMConfig = `-- name: ActivateLLMConfig :exec
UPDATE llm_configurations
SET is_active = true, updated_at = $1
WHERE id = $2
`

type ActivateLLMConfigParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        string             `json:"id"`
}

func (q *Queries) ActivateLLMConfig(ctx context.Context, arg ActivateLLMConfigParams) error {
	_, err := q.db.Exec(ctx, activateLLMConfig, arg.UpdatedAt, arg.ID)
	return err
}

const countLLMConfigs = `-- name: CountLLMConfigs :one
SELECT COUNT(*) FROM llm_configurations
`

func (q *Queries) CountLLMConfigs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLLMConfigs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLLMConfig = `-- name: CreateLLMConfig :exec
INSERT INTO llm_configurations (id, type, name, base_url, model, timeout_ms, api_key_ciphertext, options, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateLLMConfigParams struct {
	ID               string             `json:"id"`
	Type             string             `json:"type"`
	Name             string             `json:"name"`
	BaseUrl          string             `json:"base_url"`
	Model            string             `json:"model"`
	TimeoutMs        int32              `json:"timeout_ms"`
	ApiKeyCiphertext pgtype.Text        `json:"api_key_ciphertext"`
	Options          []byte             `json:"options"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateLLMConfig(ctx context.Context, arg CreateLLMConfigParams) error {
	_, err := q.db.Exec(ctx, createLLMConfig,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.BaseUrl,
		arg.Model,
		arg.TimeoutMs,
		arg.ApiKeyCiphertext,
		arg.Options,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deactivateAllLLMConfigs = `-- name: DeactivateAllLLMConfigs :exec
UPDATE llm_configurations
SET is_active = false, updated_at = $1
WHERE is_active = true
`

func (q *Queries) DeactivateAllLLMConfigs(ctx context.Context, updatedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deactivateAllLLMConfigs, updatedAt)
	return err
}

const deleteLLMConfig = `-- name: DeleteLLMConfig :exec
DELETE FROM llm_configurations
WHERE id = $1
`

func (q *Queries) DeleteLLMConfig(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLLMConfig, id)
	return err
}

const findActiveLLMConfig = `-- name: FindActiveLLMConfig :one
SELECT id, type, name, base_url, model, timeout_ms, api_key_ciphertext, options, is_active, created_at, updated_at
FROM llm_configurations
WHERE is_active = true
LIMIT 1
`

func (q *Queries) FindActiveLLMConfig(ctx context.Context) (LlmConfiguration, error) {
	row := q.db.QueryRow(ctx, findActiveLLMConfig)
	var i LlmConfiguration
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.BaseUrl,
		&i.Model,
		&i.TimeoutMs,
		&i.ApiKeyCiphertext,
		&i.Options,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findLLMConfig = `-- name: FindLLMConfig :one
SELECT id, type, name, base_url, model, timeout_ms, api_key_ciphertext, options, is_active, created_at, updated_at
FROM llm_configurations
WHERE id = $1
`

func (q *Queries) FindLLMConfig(ctx context.Context, id string) (LlmConfiguration, error) {
	row := q.db.QueryRow(ctx, findLLMConfig, id)
	var i LlmConfiguration
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.BaseUrl,
		&i.Model,
		&i.TimeoutMs,
		&i.ApiKeyCiphertext,
		&i.Options,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLLMConfigs = `-- name: ListLLMConfigs :many
SELECT id, type, name, base_url, model, timeout_ms, api_key_ciphertext, options, is_active, created_at, updated_at
FROM llm_configurations
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListLLMConfigsParams struct {
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

func (q *Queries) ListLLMConfigs(ctx context.Context, arg ListLLMConfigsParams) ([]LlmConfiguration, error) {
	rows, err := q.db.Query(ctx, listLLMConfigs, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LlmConfiguration{}
	for rows.Next() {
		var i LlmConfiguration
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.BaseUrl,
			&i.Model,
			&i.TimeoutMs,
			&i.ApiKeyCiphertext,
			&i.Options,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLLMConfig = `-- name: UpdateLLMConfig :exec
UPDATE llm_configurations
SET name = $1,
    base_url = $2,
    model = $3,
    timeout_ms = $4,
    api_key_ciphertext = $5,
    options = $6,
    updated_at = $7
WHERE id = $8
`

type UpdateLLMConfigParams struct {
	Name             string             `json:"name"`
	BaseUrl          string             `json:"base_url"`
	Model            string             `json:"model"`
	TimeoutMs        int32              `json:"timeout_ms"`
	ApiKeyCiphertext pgtype.Text        `json:"api_key_ciphertext"`
	Options          []byte             `json:"options"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ID               string             `json:"id"`
}

func (q *Queries) UpdateLLMConfig(ctx context.Context, arg UpdateLLMConfigParams) error {
	_, err := q.db.Exec(ctx, updateLLMConfig,
		arg.Name,
		arg.BaseUrl,
		arg.Model,
		arg.TimeoutMs,
		arg.ApiKeyCiphertext,
		arg.Options,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
