// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Analysis struct {
	ID                 string             `json:"id"`
	Summary            string             `json:"summary"`
	Severity           string             `json:"severity"`
	Confidence         string             `json:"confidence"`
	AffectedServices   []string           `json:"affected_services"`
	Evidence           []byte             `json:"evidence"`
	DetectedAnomalies  []string           `json:"detected_anomalies"`
	PossibleRootCauses []byte             `json:"possible_root_causes"`
	RecommendedActions []byte             `json:"recommended_actions"`
	CodeLevelInsights  []string           `json:"code_level_insights"`
	MissingEvidence    []string           `json:"missing_evidence"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type AnalysisChatFeedback struct {
	AnalysisID string             `json:"analysis_id"`
	MessageID  int64              `json:"message_id"`
	Useful     bool               `json:"useful"`
	Reason     string             `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AnalysisChatMessage struct {
	ID         int64              `json:"id"`
	AnalysisID string             `json:"analysis_id"`
	Role       string             `json:"role"`
	Content    string             `json:"content"`
	Evidence   []byte             `json:"evidence"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AnalysisJob struct {
	ID              string             `json:"id"`
	AnalysisID      pgtype.Text        `json:"analysis_id"`
	Status          string             `json:"status"`
	Request         []byte             `json:"request"`
	ErrorMessage    string             `json:"error_message"`
	Attempt         int32              `json:"attempt"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	Phase           string             `json:"phase"`
	ProgressPercent int32              `json:"progress_percent"`
	PhaseStartedAt  pgtype.Timestamptz `json:"phase_started_at"`
}
