// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Analysis struct {
	ID                 string             `json:"id"`
	Summary            string             `json:"summary"`
	Severity           string             `json:"severity"`
	Confidence         string             `json:"confidence"`
	AffectedServices   []string           `json:"affected_services"`
	Evidence           []byte             `json:"evidence"`
	DetectedAnomalies  []string           `json:"detected_anomalies"`
	PossibleRootCauses []byte             `json:"possible_root_causes"`
	RecommendedActions []byte             `json:"recommended_actions"`
	CodeLevelInsights  []string           `json:"code_level_insights"`
	MissingEvidence    []string           `json:"missing_evidence"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	TraceID            string             `json:"trace_id"`
}

type AnalysisChatFeedback struct {
	AnalysisID string             `json:"analysis_id"`
	MessageID  int64              `json:"message_id"`
	Useful     bool               `json:"useful"`
	Reason     string             `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AnalysisChatMessage struct {
	ID         int64              `json:"id"`
	AnalysisID string             `json:"analysis_id"`
	Role       string             `json:"role"`
	Content    string             `json:"content"`
	Evidence   []byte             `json:"evidence"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AnalysisJob struct {
	ID              string             `json:"id"`
	AnalysisID      pgtype.Text        `json:"analysis_id"`
	Status          string             `json:"status"`
	Request         []byte             `json:"request"`
	ErrorMessage    string             `json:"error_message"`
	Attempt         int32              `json:"attempt"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	Phase           string             `json:"phase"`
	ProgressPercent int32              `json:"progress_percent"`
	PhaseStartedAt  pgtype.Timestamptz `json:"phase_started_at"`
}

type ApiKey struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	KeyHash     string             `json:"key_hash"`
	Scope       string             `json:"scope"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	Description pgtype.Text        `json:"description"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Scopes      []string           `json:"scopes"`
}

type AuditLog struct {
	ID           int64              `json:"id"`
	RequestID    string             `json:"request_id"`
	ApiKeyID     string             `json:"api_key_id"`
	Actor        string             `json:"actor"`
	Method       string             `json:"method"`
	Path         string             `json:"path"`
	Status       int32              `json:"status"`
	DurationMs   int64              `json:"duration_ms"`
	Remote       string             `json:"remote"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	Metadata     []byte             `json:"metadata"`
}

type LlmConfiguration struct {
	ID               string             `json:"id"`
	Type             string             `json:"type"`
	Name             string             `json:"name"`
	BaseUrl          string             `json:"base_url"`
	Model            string             `json:"model"`
	TimeoutMs        int32              `json:"timeout_ms"`
	ApiKeyCiphertext pgtype.Text        `json:"api_key_ciphertext"`
	Options          []byte             `json:"options"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ProviderConfiguration struct {
	ID                    string             `json:"id"`
	Type                  string             `json:"type"`
	Name                  string             `json:"name"`
	Url                   string             `json:"url"`
	TimeoutMs             int32              `json:"timeout_ms"`
	Signals               []string           `json:"signals"`
	Options               []byte             `json:"options"`
	CredentialsCiphertext pgtype.Text        `json:"credentials_ciphertext"`
	IsActive              bool               `json:"is_active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	FamilyID   string             `json:"family_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.Text        `json:"replaced_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                 string             `json:"id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	Role               string             `json:"role"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	MustChangePassword bool               `json:"must_change_password"`
	Preferences        []byte             `json:"preferences"`
	Name               string             `json:"name"`
}

type WebhookDelivery struct {
	ID             string             `json:"id"`
	SubscriptionID string             `json:"subscription_id"`
	Event          string             `json:"event"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempt        int32              `json:"attempt"`
	LastError      pgtype.Text        `json:"last_error"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type WebhookSubscription struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Url        string             `json:"url"`
	Secret     string             `json:"secret"`
	Event      string             `json:"event"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
}
