// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Analysis struct {
	ID                 string             `json:"id"`
	Summary            string             `json:"summary"`
	Severity           string             `json:"severity"`
	Confidence         string             `json:"confidence"`
	AffectedServices   []string           `json:"affected_services"`
	Evidence           []byte             `json:"evidence"`
	DetectedAnomalies  []string           `json:"detected_anomalies"`
	PossibleRootCauses []byte             `json:"possible_root_causes"`
	RecommendedActions []byte             `json:"recommended_actions"`
	CodeLevelInsights  []string           `json:"code_level_insights"`
	MissingEvidence    []string           `json:"missing_evidence"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type AnalysisChatMessage struct {
	ID         int64              `json:"id"`
	AnalysisID string             `json:"analysis_id"`
	Role       string             `json:"role"`
	Content    string             `json:"content"`
	Evidence   []byte             `json:"evidence"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
