// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_configurations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProviderConfigs = `-- name: CountProviderConfigs :one
SELECT COUNT(*) FROM provider_configurations
`

func (q *Queries) CountProviderConfigs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderConfigs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProviderConfig = `-- name: CreateProviderConfig :exec
INSERT INTO provider_configurations (id, type, name, url, timeout_ms, signals, options, credentials_ciphertext, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateProviderConfigParams struct {
	ID                    string             `json:"id"`
	Type                  string             `json:"type"`
	Name                  string             `json:"name"`
	Url                   string             `json:"url"`
	TimeoutMs             int32              `json:"timeout_ms"`
	Signals               []string           `json:"signals"`
	Options               []byte             `json:"options"`
	CredentialsCiphertext pgtype.Text        `json:"credentials_ciphertext"`
	IsActive              bool               `json:"is_active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProviderConfig(ctx context.Context, arg CreateProviderConfigParams) error {
	_, err := q.db.Exec(ctx, createProviderConfig,
		arg.ID,
		arg.Type,
		arg.Name,
		arg.Url,
		arg.TimeoutMs,
		arg.Signals,
		arg.Options,
		arg.CredentialsCiphertext,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProviderConfig = `-- name: DeleteProviderConfig :exec
DELETE FROM provider_configurations
WHERE id = $1
`

func (q *Queries) DeleteProviderConfig(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProviderConfig, id)
	return err
}

const findProviderConfig = `-- name: FindProviderConfig :one
SELECT id, type, name, url, timeout_ms, signals, options, credentials_ciphertext, is_active, created_at, updated_at
FROM provider_configurations
WHERE id = $1
`

func (q *Queries) FindProviderConfig(ctx context.Context, id string) (ProviderConfiguration, error) {
	row := q.db.QueryRow(ctx, findProviderConfig, id)
	var i ProviderConfiguration
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Url,
		&i.TimeoutMs,
		&i.Signals,
		&i.Options,
		&i.CredentialsCiphertext,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProviderConfigs = `-- name: ListActiveProviderConfigs :many
SELECT id, type, name, url, timeout_ms, signals, options, credentials_ciphertext, is_active, created_at, updated_at
FROM provider_configurations
WHERE is_active = true
ORDER BY name
`

func (q *Queries) ListActiveProviderConfigs(ctx context.Context) ([]ProviderConfiguration, error) {
	rows, err := q.db.Query(ctx, listActiveProviderConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderConfiguration{}
	for rows.Next() {
		var i ProviderConfiguration
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Url,
			&i.TimeoutMs,
			&i.Signals,
			&i.Options,
			&i.CredentialsCiphertext,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderConfigs = `-- name: ListProviderConfigs :many
SELECT id, type, name, url, timeout_ms, signals, options, credentials_ciphertext, is_active, created_at, updated_at
FROM provider_configurations
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListProviderConfigsParams struct {
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

func (q *Queries) ListProviderConfigs(ctx context.Context, arg ListProviderConfigsParams) ([]ProviderConfiguration, error) {
	rows, err := q.db.Query(ctx, listProviderConfigs, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderConfiguration{}
	for rows.Next() {
		var i ProviderConfiguration
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Url,
			&i.TimeoutMs,
			&i.Signals,
			&i.Options,
			&i.CredentialsCiphertext,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProviderConfigActive = `-- name: SetProviderConfigActive :exec
UPDATE provider_configurations
SET is_active = $1, updated_at = $2
WHERE id = $3
`

type SetProviderConfigActiveParams struct {
	IsActive  bool               `json:"is_active"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        string             `json:"id"`
}

func (q *Queries) SetProviderConfigActive(ctx context.Context, arg SetProviderConfigActiveParams) error {
	_, err := q.db.Exec(ctx, setProviderConfigActive, arg.IsActive, arg.UpdatedAt, arg.ID)
	return err
}

const updateProviderConfig = `-- name: UpdateProviderConfig :exec
UPDATE provider_configurations
SET name = $1,
    url = $2,
    timeout_ms = $3,
    signals = $4,
    options = $5,
    credentials_ciphertext = $6,
    updated_at = $7
WHERE id = $8
`

type UpdateProviderConfigParams struct {
	Name                  string             `json:"name"`
	Url                   string             `json:"url"`
	TimeoutMs             int32              `json:"timeout_ms"`
	Signals               []string           `json:"signals"`
	Options               []byte             `json:"options"`
	CredentialsCiphertext pgtype.Text        `json:"credentials_ciphertext"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	ID                    string             `json:"id"`
}

func (q *Queries) UpdateProviderConfig(ctx context.Context, arg UpdateProviderConfigParams) error {
	_, err := q.db.Exec(ctx, updateProviderConfig,
		arg.Name,
		arg.Url,
		arg.TimeoutMs,
		arg.Signals,
		arg.Options,
		arg.CredentialsCiphertext,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
