// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, password_hash, role, is_active, must_change_password, preferences, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateUserParams struct {
	ID                 string             `json:"id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	Role               string             `json:"role"`
	IsActive           bool               `json:"is_active"`
	MustChangePassword bool               `json:"must_change_password"`
	Preferences        []byte             `json:"preferences"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.IsActive,
		arg.MustChangePassword,
		arg.Preferences,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, password_hash, role, is_active, must_change_password, preferences, created_at, updated_at, last_login_at
FROM users
WHERE email = $1
`

type FindUserByEmailRow struct {
	ID                 string             `json:"id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	Role               string             `json:"role"`
	IsActive           bool               `json:"is_active"`
	MustChangePassword bool               `json:"must_change_password"`
	Preferences        []byte             `json:"preferences"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.MustChangePassword,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, password_hash, role, is_active, must_change_password, preferences, created_at, updated_at, last_login_at
FROM users
WHERE id = $1
`

type FindUserByIDRow struct {
	ID                 string             `json:"id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	Role               string             `json:"role"`
	IsActive           bool               `json:"is_active"`
	MustChangePassword bool               `json:"must_change_password"`
	Preferences        []byte             `json:"preferences"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) FindUserByID(ctx context.Context, id string) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.MustChangePassword,
		&i.Preferences,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, role, is_active, must_change_password, preferences, created_at, updated_at, last_login_at
FROM users
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

type ListUsersRow struct {
	ID                 string             `json:"id"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	Role               string             `json:"role"`
	IsActive           bool               `json:"is_active"`
	MustChangePassword bool               `json:"must_change_password"`
	Preferences        []byte             `json:"preferences"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.MustChangePassword,
			&i.Preferences,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users
SET is_active = $1, updated_at = $2
WHERE id = $3
`

type SetUserActiveParams struct {
	IsActive  bool               `json:"is_active"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        string             `json:"id"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.Exec(ctx, setUserActive, arg.IsActive, arg.UpdatedAt, arg.ID)
	return err
}

const setUserMustChangePassword = `-- name: SetUserMustChangePassword :exec
UPDATE users
SET must_change_password = $1, updated_at = $2
WHERE id = $3
`

type SetUserMustChangePasswordParams struct {
	MustChangePassword bool               `json:"must_change_password"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ID                 string             `json:"id"`
}

func (q *Queries) SetUserMustChangePassword(ctx context.Context, arg SetUserMustChangePasswordParams) error {
	_, err := q.db.Exec(ctx, setUserMustChangePassword, arg.MustChangePassword, arg.UpdatedAt, arg.ID)
	return err
}

const touchUserLastLogin = `-- name: TouchUserLastLogin :exec
UPDATE users
SET last_login_at = $1, updated_at = $2
WHERE id = $3
`

type TouchUserLastLoginParams struct {
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          string             `json:"id"`
}

func (q *Queries) TouchUserLastLogin(ctx context.Context, arg TouchUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, touchUserLastLogin, arg.LastLoginAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1, must_change_password = false, updated_at = $2
WHERE id = $3
`

type UpdateUserPasswordParams struct {
	PasswordHash string             `json:"password_hash"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ID           string             `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
UPDATE users
SET preferences = $1, updated_at = $2
WHERE id = $3
`

type UpdateUserPreferencesParams struct {
	Preferences []byte             `json:"preferences"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          string             `json:"id"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, updateUserPreferences, arg.Preferences, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET email = $1, updated_at = $2
WHERE id = $3
`

type UpdateUserProfileParams struct {
	Email     string             `json:"email"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        string             `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile, arg.Email, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET role = $1, updated_at = $2
WHERE id = $3
`

type UpdateUserRoleParams struct {
	Role      string             `json:"role"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        string             `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.Role, arg.UpdatedAt, arg.ID)
	return err
}
