// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_deliveries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :exec
INSERT INTO webhook_deliveries (id, subscription_id, event, payload, status, attempt, next_attempt_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateWebhookDeliveryParams struct {
	ID             string             `json:"id"`
	SubscriptionID string             `json:"subscription_id"`
	Event          string             `json:"event"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempt        int32              `json:"attempt"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, createWebhookDelivery,
		arg.ID,
		arg.SubscriptionID,
		arg.Event,
		arg.Payload,
		arg.Status,
		arg.Attempt,
		arg.NextAttemptAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findWebhookDelivery = `-- name: FindWebhookDelivery :one
SELECT id, subscription_id, event, payload, status, attempt, last_error, response_status, next_attempt_at, delivered_at, created_at, updated_at
FROM webhook_deliveries
WHERE id = $1
`

func (q *Queries) FindWebhookDelivery(ctx context.Context, id string) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, findWebhookDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.Event,
		&i.Payload,
		&i.Status,
		&i.Attempt,
		&i.LastError,
		&i.ResponseStatus,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingWebhookDeliveries = `-- name: ListPendingWebhookDeliveries :many
SELECT id, subscription_id, event, payload, status, attempt, last_error, response_status, next_attempt_at, delivered_at, created_at, updated_at
FROM webhook_deliveries
WHERE status = 'pending' AND (next_attempt_at IS NULL OR next_attempt_at <= $1)
ORDER BY created_at ASC
LIMIT $2
`

type ListPendingWebhookDeliveriesParams struct {
	Cutoff      pgtype.Timestamptz `json:"cutoff"`
	ResultLimit int32              `json:"result_limit"`
}

func (q *Queries) ListPendingWebhookDeliveries(ctx context.Context, arg ListPendingWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listPendingWebhookDeliveries, arg.Cutoff, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.Event,
			&i.Payload,
			&i.Status,
			&i.Attempt,
			&i.LastError,
			&i.ResponseStatus,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, subscription_id, event, payload, status, attempt, last_error, response_status, next_attempt_at, delivered_at, created_at, updated_at
FROM webhook_deliveries
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListWebhookDeliveriesParams struct {
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.Event,
			&i.Payload,
			&i.Status,
			&i.Attempt,
			&i.LastError,
			&i.ResponseStatus,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDeliveryDelivered = `-- name: MarkWebhookDeliveryDelivered :exec
UPDATE webhook_deliveries
SET status = 'delivered', response_status = $1, delivered_at = $2, updated_at = $3, last_error = NULL, next_attempt_at = NULL
WHERE id = $4
`

type MarkWebhookDeliveryDeliveredParams struct {
	ResponseStatus pgtype.Int4        `json:"response_status"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ID             string             `json:"id"`
}

func (q *Queries) MarkWebhookDeliveryDelivered(ctx context.Context, arg MarkWebhookDeliveryDeliveredParams) error {
	_, err := q.db.Exec(ctx, markWebhookDeliveryDelivered,
		arg.ResponseStatus,
		arg.DeliveredAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const markWebhookDeliveryFailed = `-- name: MarkWebhookDeliveryFailed :exec
UPDATE webhook_deliveries
SET status = 'failed', attempt = $1, last_error = $2, response_status = $3, next_attempt_at = NULL, updated_at = $4
WHERE id = $5
`

type MarkWebhookDeliveryFailedParams struct {
	Attempt        int32              `json:"attempt"`
	LastError      pgtype.Text        `json:"last_error"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ID             string             `json:"id"`
}

func (q *Queries) MarkWebhookDeliveryFailed(ctx context.Context, arg MarkWebhookDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookDeliveryFailed,
		arg.Attempt,
		arg.LastError,
		arg.ResponseStatus,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const scheduleWebhookDeliveryRetry = `-- name: ScheduleWebhookDeliveryRetry :exec
UPDATE webhook_deliveries
SET status = 'pending', attempt = $1, last_error = $2, response_status = $3, next_attempt_at = $4, updated_at = $5
WHERE id = $6
`

type ScheduleWebhookDeliveryRetryParams struct {
	Attempt        int32              `json:"attempt"`
	LastError      pgtype.Text        `json:"last_error"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ID             string             `json:"id"`
}

func (q *Queries) ScheduleWebhookDeliveryRetry(ctx context.Context, arg ScheduleWebhookDeliveryRetryParams) error {
	_, err := q.db.Exec(ctx, scheduleWebhookDeliveryRetry,
		arg.Attempt,
		arg.LastError,
		arg.ResponseStatus,
		arg.NextAttemptAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
