// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_subscriptions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookSubscription = `-- name: CreateWebhookSubscription :exec
INSERT INTO webhook_subscriptions (id, name, url, secret, event, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateWebhookSubscriptionParams struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Url       string             `json:"url"`
	Secret    string             `json:"secret"`
	Event     string             `json:"event"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createWebhookSubscription,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.Event,
		arg.CreatedAt,
	)
	return err
}

const disableWebhookSubscription = `-- name: DisableWebhookSubscription :exec
UPDATE webhook_subscriptions
SET disabled_at = $1
WHERE id = $2 AND disabled_at IS NULL
`

type DisableWebhookSubscriptionParams struct {
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
	ID         string             `json:"id"`
}

func (q *Queries) DisableWebhookSubscription(ctx context.Context, arg DisableWebhookSubscriptionParams) error {
	_, err := q.db.Exec(ctx, disableWebhookSubscription, arg.DisabledAt, arg.ID)
	return err
}

const listActiveWebhooksForEvent = `-- name: ListActiveWebhooksForEvent :many
SELECT id, name, url, secret, event, created_at, disabled_at
FROM webhook_subscriptions
WHERE event = $1 AND disabled_at IS NULL
`

func (q *Queries) ListActiveWebhooksForEvent(ctx context.Context, event string) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listActiveWebhooksForEvent, event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Event,
			&i.CreatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptions = `-- name: ListWebhookSubscriptions :many
SELECT id, name, url, secret, event, created_at, disabled_at
FROM webhook_subscriptions
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListWebhookSubscriptionsParams struct {
	ResultOffset int32 `json:"result_offset"`
	ResultLimit  int32 `json:"result_limit"`
}

func (q *Queries) ListWebhookSubscriptions(ctx context.Context, arg ListWebhookSubscriptionsParams) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhookSubscriptions, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Event,
			&i.CreatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
